---
- name: (re)start libvirt daemon
  service:
    name: libvirtd
    state: restarted

- name: check if openshift nat already exists
  virt_net:
    command: list_nets
  register: all_nets

- name: destroy old openshift nat
  virt_net:
    command: destroy
    name: openshift
  when: "'openshift' in all_nets.list_nets"

- name: undefine old openshift nat
  virt_net:
    command: undefine
    name: openshift
  when: "'openshift' in all_nets.list_nets"

- name: define openshift nat
  virt_net:
    command: define
    name: openshift
    xml: "{{lookup('file', '{{ files.base }}/conf/libvirtd.nat-openshift.xml')}}"

- name: start openshift nat
  virt_net:
    command: create
    name: openshift
    state: active

- name: autostart openshift nat
  virt_net:
    name: openshift
    autostart: yes

- name: list openshift storage pool
  virt_pool:
    command: list_pools
  register: all_pools

- name: destroy openshift storage pool
  virt_pool:
    command: destroy
    name: openshift
  when: "'openshift' in all_pools.list_pools"
  ignore_errors: yes

- name: delete openshift storage pool
  virt_pool:
    command: delete
    name: openshift
  when: "'openshift' in all_pools.list_pools"
  ignore_errors: yes

- name: clean openshift storage pool folder
  file:
    path: "{{ libvirt_pool.path }}"
    state: absent
  when: "'openshift' in all_pools.list_pools"

- name: create openshift storage pool
  virt_pool:
    command: define
    name: openshift
    xml: "{{lookup('file', '{{ files.base }}/conf/libvirtd.pool-openshift.xml')}}"

- name: create openshift storage pool
  file:
    path: "{{ libvirt_pool.path }}"
    state: directory
    mode: g+rx,o+rx

- name: autostart openshift storage pool
  virt_pool:
    name: openshift
    autostart: yes

- name: start openshift storage pool
  virt_pool:
    command: create
    name: openshift
    state: active
